// samples/vue_rss_espn/src/App.vue
<template>
  <div id="app">
    <div v-if="!loaded">Loading ...</div>
    <Item v-for="(item, index) in items"
      v-bind:key=index
      v-bind:title=item.title
      v-bind:link=item.link
      v-bind:image=item.image
      v-bind:desc=item.description>
    </Item>
  </div>
</template>

<script>
import Item from './components/Item.vue'
import axios from 'axios'

export default {
  name: 'app',
  data () {
    return {
      items: null,
      loaded: false
    }
  },
  components : {Item},
  mounted () {
    /*
      Call back-end to transform XML RSS feed to JSON & bypass CORS restrictions.
    */
    axios
      .get('https://flannel-glade.glitch.me', {
        params: {
          rss: 'http://www.espn.com/blog/feed?blog=afcsouth'
        }
      })
      .then(response => {
        this.items = response.data.rss.channel.item;
        this.loaded = true;
      })
      .catch(error => {
        console.log(error)
      })
  }
 }
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin: 2% auto;
  max-width: 800px;
}
</style>

// samples/react_podcast_espn/src/App.js
import React, { Component } from 'react';

import './App.css';
import axios from 'axios';
import Podcasts from './Podcasts.js';
import FilePlayer from 'react-player/lib/players/FilePlayer';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      rss: [],
      isLoaded: false,
      url: "",
      selected: -1,
      playing: false
    };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(url, selected, e) {
    this.setState(
      {
        url: url,
        playing: true,
        selected: selected
      });
  }

  /* Retrieve the JSON version of the RSS feed from the back-end & overcome CORS  */
  componentDidMount() {
    axios.get("https://flannel-glade.glitch.me", {
      params: {
        rss: "http://www.espn.com/espnradio/feeds/rss/podcast.xml?id=2942325"
      }
    })
    .then((response) => {
      this.setState({
        rss: response.data.rss,
        isLoaded: true
      });
    })
  }

  render() {
    const spacer = <div className="mediaPlayer"></div>

    if (!this.state.isLoaded) {
      return (
        <div className="App">
          <div>Loading</div>
          <div class="lds-facebook"><div></div><div></div><div></div></div>
        </div>
      );
    } else {
      return (
        <div className="App">
          <div className="Header">
            <img src={this.state.rss.channel.image.url} alt=""></img>
            <div className="HeaderText">
              <div className="Title">{this.state.rss.channel.title}</div>
              <div>{this.state.rss.channel.description}</div>
            </div>
          </div>

          {!this.state.playing ? spacer : "" /* Reserve space for FilePlayer until url is loaded */}
          <FilePlayer className="mediaPlayer" url={this.state.url} controls 
            playing={this.state.playing} height="40px" width="100%"/>

          <Podcasts items={this.state.rss.channel.item} 
            clickFunc={this.handleClick}
            selected={this.state.selected}/>
        </div>
      );
    }
  }
}

export default App;
